### ISSUE TITLE
Design a password reset page where the user can enter a new password

### ISSUE THREAD

**Issue by Anas-Jamjoum** [mosa-salman/robotics-program-portal#37]
## Issue Description:
Designing a password reset page where administrators can enter a new password is crucial for ensuring a secure and user-friendly password reset process. This issue focuses on creating an intuitive and visually appealing interface that allows administrators to set a new password securely after initiating the password reset procedure.

## Objective:
The objective of this issue is to design a password reset page for administrators, enabling them to enter a new password securely as part of the password reset process.

## Additional Considerations:
Consider providing visual feedback or indicators to confirm successful password changes and reassure administrators that their new passwords have been set.
Ensure that the password reset page complies with accessibility standards, making it usable by individuals with disabilities.

## Outcome:
By designing a password reset page for administrators, we aim to provide a secure and user-friendly interface for setting new passwords as part of the password reset process. The finalized design will incorporate input fields for the new password and password confirmation, along with guidance on creating strong and secure passwords. Thorough testing and user feedback will ensure that the password reset page meets the requirements and expectations of administrators, enhancing the overall security and usability of the system.

**Comment by mosa-salman** [comment]
This is the default reset password, need to research whether in order to customize it, what are the requirements.


![Image](https://github.com/mosa-salman/robotics-program-portal/assets/55544612/f70150e3-df53-4969-8c11-26b89007acf6)



![Image](https://github.com/mosa-salman/robotics-program-portal/assets/55544612/12c30631-8aaa-4f7f-827b-1b7bb98dce69)



![Image](https://github.com/mosa-salman/robotics-program-portal/assets/55544612/bbde7878-9b16-4570-bd65-eecf114f77f8)
